kind: ConfigMap
metadata:
  name:  cm-configure-stackrox
  annotations:
    argocd.argoproj.io/sync-wave: "3"
apiVersion: v1
data:
  configure-stackrox-play.yaml: |
    - hosts: localhost
      tasks:
      - name: Get Central route
        k8s_info:
          kind: Route
          api_version: route.openshift.io/v1
          namespace: "{{ $.Values.stackrox.namespace }}"
          name: central
        register: r_stackrox_central_route
        retries: 10
        delay: 20
        until:
        - r_stackrox_central_route.resources[0].spec.host is defined

      - name: Get Central secret
        k8s_info:
          kind: Secret
          api_version: v1
          namespace: "{{ $.Values.stackrox.namespace }}"
          name: acs-password
        register: r_central_secret
        retries: 10
        delay: 20
        until:
        - r_central_secret.resources is defined
        - r_central_secret.resources | length > 0

      - name: Store central route as a fact
        set_fact:
          f_stackrox_central_addr: "{{ `{{ r_stackrox_central_route.resources[0].spec.host }}` }}"