{{- $centralPassword := randAlphaNum 8 -}}
apiVersion: v1
kind: Secret
metadata:
  name: acs-password
  namespace: "{{ $.Values.stackrox.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
{{ if not $.Values.stackrox.central.password }}
  password: "{{ centralPassword | b64enc }}"
{{ else }}
  password: "{{ $.Values.stackrox.central.password | b64enc }}"
{{ end }}
type: Opaque