apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhacs-operator-og
  namespace: "{{ $.Values.rhacs.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec: {}
