apiVersion: batch/v1
kind: Job
metadata:
  name: playbook-job
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: playbook
        command:
        - /bin/bash
        - '-c'
        - |
            set -x
            ansible-playbook -i localhost /plays/playbook.yaml
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
          - mountPath: /plays
            name: vol-playbook
      restartPolicy: Never
      serviceAccount: playbook-runner
      volumes:
      - name: vol-playbook
        configMap:
          name: playbook-cm