kind: ConfigMap
metadata:
  name:  playbook-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
apiVersion: v1
data:
  playbook.yaml: |
    - hosts: localhost
      vars:
        ocp4_workload_rhacs_authentication_central_stackrox_url: {{ $.Values.stackrox.central.url | default "" | quote }}
        ocp4_workload_rhacs_authentication_central_namespace: {{ $.Values.stackrox.namespace | default "" | quote }}
        ocp4_workload_rhacs_authentication_central_admin_username: {{ $.Values.stackrox.central.adminUser | default "" | quote }}
        ocp4_workload_rhacs_authentication_central_admin_password: {{ $.Values.stackrox.central.adminPassword | default "" | quote }}
        ocp4_workload_rhacs_authentication_central_minimum_access_role: {{ $.Values.stackrox.central.accessRole | default "" | quote }}
      tasks:
      - name: Set stackrox url if url not defined
        when: ocp4_workload_rhacs_authentication_central_stackrox_url | default("") | length == 0
        block:
          - name: Get stackrox route
            k8s_info:
              api_version: route.openshift.io/v1
              kind: Route
              namespace: "{{ `{{ ocp4_workload_rhacs_authentication_central_namespace }}` }}"
              name: central
            register: r_stackrox_route

          - name: Set stackrox url
            set_fact:
              ocp4_workload_rhacs_authentication_central_stackrox_url: https://{{ `{{ r_stackrox_route.resources[0].spec.host }}` }}

      - name: Create Identity Provider in ACS
        uri:
          url: "{{ `{{ ocp4_workload_rhacs_authentication_central_stackrox_url }}` }}/v1/authProviders"
          user: "{{ `{{ ocp4_workload_rhacs_authentication_central_admin_username }}` }}"
          password: "{{ `{{ ocp4_workload_rhacs_authentication_central_admin_password }}` }}"
          force_basic_auth: true
          method: POST
          headers:
            Content-Type: "application/json"
          body_format: json
          body:
            name: "openshift-oauth"
            type: "openshift"
            enabled: true
            active: true
          validate_certs: false
        register: r_idp_response

      - name: Create group for Identity Provider
        uri:
          url: "{{ `{{ ocp4_workload_rhacs_authentication_central_stackrox_url }}` }}/v1/groups"
          user: "{{ `{{ ocp4_workload_rhacs_authentication_central_admin_username }}` }}"
          password: "{{ `{{ ocp4_workload_rhacs_authentication_central_admin_password }}` }}"
          force_basic_auth: true
          method: POST
          headers:
            Content-Type: "application/json"
          body_format: json
          body:
            props:
              authProviderId: "{{ `{{ r_idp_response.json.id }}` }}"
            roleName: "{{ `{{ ocp4_workload_rhacs_authentication_central_minimum_access_role }}` }}"
          validate_certs: false