{{- $centralPassword := randAlphaNum 8 -}}
apiVersion: v1
kind: Secret
metadata:
  name: acs-password
  namespace: "{{ $.Values.stackrox.namespace }}"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  password: "{{ $.Values.stackrox.central.adminPassword | default $centralPassword | b64enc }}"
type: Opaque