kind: ConfigMap
metadata:
  name: playbook-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
apiVersion: v1
data:
  playbook.yaml: |
    - hosts: localhost
      vars:
        ocp4_workload_rhacs_central_admin_password: {{ $.Values.rhacs.central.adminPassword | default "" | quote }}
      tasks:
      - name: Create RHACS operator namespace
        k8s:
          state: present
          api_version: v1
          kind: Namespace
          name: rhacs-operator

      - name: Create RHACS operator group
        k8s:
          state: present
          definition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: rhacs-operator-og
              namespace: rhacs-operator
            spec: {}

      - name: Create RHACS operator subscription
        k8s:
          state: present
          definition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: rhacs-operator
              namespace: rhacs-operator
            spec:
              channel: "{{ $.Values.rhacs.operator.channel }}"
            {{- if $.Values.rhacs.operator.startingCSV }}
              startingCSV: "{{ $.Values.rhacs.operator.startingCSV }}"
            {{- end }}
              installPlanApproval: Automatic
              name: rhacs-operator
              source: redhat-operators
              sourceNamespace: openshift-marketplace

      - name: Check if operator installed
        shell: |
          oc get csv -n rhacs-operator --no-headers | grep rhacs-operator | awk '{print $NF}'
        register: r_operator_installed
        retries: 30
        delay: 10
        until:
        - r_operator_installed.stdout == 'Succeeded'

      - name: Create Central Namespace
        k8s:
          state: present
          api_version: v1
          kind: Namespace
          name: stackrox

      - name: Generate random password for Central admin
        when: not ocp4_workload_rhacs_central_admin_password
        set_fact:
          ocp4_workload_rhacs_central_admin_password: >-
              {{ `{{ lookup('password', '/dev/null chars=ascii_letters,digits '
                ~ 'length=18'
              ) }}` }}

      - name: Create Secret for Central admin password
        k8s:
          state: present
          definition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: acs-password
              namespace: stackrox
            data:
              password: "{{ `{{ ocp4_workload_rhacs_central_admin_password | b64encode }}` }}"
            type: Opaque

      - name: Create Central via CR
        k8s:
          state: present
          definition:
            apiVersion: platform.stackrox.io/v1alpha1
            kind: Central
            metadata:
              namespace: stackrox
              name: stackrox-central-services
            spec:
              central:
                adminPasswordSecret:
                  name: acs-password
                exposure:
                  loadBalancer:
                    enabled: false
                    port: 443
                  nodePort:
                    enabled: false
                  route:
                    enabled: true
                persistence:
                  persistentVolumeClaim:
                    claimName: stackrox-db
              egress:
                connectivityPolicy: Online
              scanner:
                analyzer:
                  scaling:
                    autoScaling: Disabled
                    replicas: 1
                scannerComponent: Enabled

      - name: Get Central route
        k8s_info:
          kind: Route
          api_version: route.openshift.io/v1
          namespace: stackrox
          name: central
        register: r_stackrox_central_route
        retries: 10
        delay: 20
        until:
        - r_stackrox_central_route.resources[0].spec.host is defined

      - name: Store central route as a fact
        set_fact:
          f_stackrox_central_addr: "{{ `{{ r_stackrox_central_route.resources[0].spec.host }}` }}"

      - name: Wait for Central availability
        uri:
          url: "https://{{ `{{ f_stackrox_central_addr }}` }}/v1/ping"
          method: GET
          user: "{{ $.Values.stackrox.central.adminUser }}"
          password: "{{ `{{ ocp4_workload_rhacs_central_admin_password | b64decode }}` }}"
          force_basic_auth: true
          validate_certs: false
        register: result
        until: result.status == 200
        retries: 30
        delay: 20

      - name: Get cluster init bundle
        uri:
          url: "https://{{ `{{ f_stackrox_central_addr }}` }}/v1/cluster-init/init-bundles"
          body: "{ \"name\": \"prod-{{ `{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}` }}\"}"
          method: POST
          user: "{{ $.Values.stackrox.central.adminUser }}"
          password: "{{ `{{ ocp4_workload_rhacs_central_admin_password | b64decode }}` }}"
          body_format: json
          force_basic_auth: true
          validate_certs: false
        register: r_stackrox_cluster_init_response

      - name: Store cluster init bundle as a fact
        set_fact:
          f_stackrox_bundle: "{{ `{{ r_stackrox_cluster_init_response.json.kubectlBundle | b64decode }}` }}"

      - name: Create init-bundle secrets
        k8s:
          namespace: stackrox
          state: present
          definition: "{{ `{{ f_stackrox_bundle }}` }}"

      - name: Install Sensor on OpenShift Container Platform
        k8s:
          state: present
          definition:
            apiVersion: platform.stackrox.io/v1alpha1
            kind: SecuredCluster
            metadata:
              namespace: stackrox
              name: stackrox-secured-cluster-services
            spec:
              clusterName: production
              admissionControl:
                listenOnCreates: true
                listenOnEvents: true
                listenOnUpdates: true
                bypass: BreakGlassAnnotation
                timeoutSeconds: 3
                contactImageScanners: ScanIfMissing
              perNode:
                collector:
                  collection: KernelModule
                  imageFlavor: Regular
                taintToleration: TolerateTaints

      - name: Wait for ready sensor
        k8s_info:
          name: sensor
          kind: Deployment
          api_version: apps/v1
          namespace: stackrox
        register: r_stackrox_sensor_deployment
        until:
        - r_stackrox_sensor_deployment.resources[0].status.readyReplicas is defined
        - r_stackrox_sensor_deployment.resources[0].status.readyReplicas | int >= 1
        delay: 20
        retries: 15

      - name: For fun, create a link in the OpenShift Console
        k8s:
          state: present
          definition:
            apiVersion: console.openshift.io/v1
            kind: ConsoleLink
            metadata:
              name: acs-console-link
            spec:
              applicationMenu:
                imageURL: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg'
                section: Red Hat Applications
              href: 'https://{{ `{{ f_stackrox_central_addr }}` }}'
              location: ApplicationMenu
              text: Red Hat Advanced Cluster Security for Kubernetes