kind: ConfigMap
metadata:
  name:  files-cm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
apiVersion: v1
data:
  oauth-htpasswd.yaml: |
    ---
    apiVersion: config.openshift.io/v1
    kind: OAuth
    metadata:
      name: cluster
    spec:
      identityProviders:
      - name: htpasswd_provider
        challenge: true
        login: true
        mappingMethod: claim
        type: HTPasswd
        htpasswd:
          fileData:
            name: htpasswd
