kind: ConfigMap
metadata:
  name:  templates-cm
  annotations:
    argocd.argoproj.io/sync-wave: "3"
apiVersion: v1
data:
  secret-htpasswd.yaml.j2: |
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: htpasswd
      namespace: openshift-config
    type: Opaque
    data:
      htpasswd: {{ `{{ r_htpasswd_file['content'] }}` }}
  cluster_role_binding.yaml.j2: |
    ---
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: "cluster-admin-{{ `{{ ocp4_workload_authentication_admin_user }}` }}"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-admin
    subjects:
    - apiGroup: rbac.authorization.k8s.io
      kind: User
      name: "{{ `{{ocp4_workload_authentication_admin_user }}` }}"
